input_file: '/gsm8k.jsonl'
task_name: 'math'
file: 'math_500'
output_file: 'test2.jsonl'
served_model_name: 'Qwen2-3B-Instruct'
openai_api_key: 'EMPTY'
openai_api_base: 'http://localhost:80/v1'
propose_method: 'llama'
value_method: 'local'
mode: 'mcts'
worker_number: 64
temperature: 0.7
time_limit: null
iteration_limit: 8
roll_policy: 'greedy'
exploration_constant: 0.4
roll_forward_steps: 2
end_gate: 0.9
branch: 3
roll_branch: 1
inf: 0.8
evaluate: 'math'
alpha: 0.5
visualize: false
use_case_prompt: false
use_reflection: 'simple'
low: 0
high: 1
algorithm: 'dfs'
select_branch: 2
max_depth: 8
select_method: 'greedy'
consistency: true
